### ISSUE TITLE
Outdated ICU

### ISSUE THREAD

**Issue by marcelklehr** [TRowbotham/URL-Parser#6]
First up: I really love this library. After a long search it was exactly what I needed.

Unfortunately, there are hosters our there that offer php 7.1+ with an outdated ICU version, which [causes](https://stackoverflow.com/questions/48465775/swiftmailer-use-of-undefined-constant-intl-idna-variant-uts46#49000417) the usage of certain IDN constants to fail. Would you be amendable to implementing a similar fix to [this one](https://github.com/PrestaShop/PrestaShop/pull/11995)?

**Comment by TRowbotham** [comment]
Thanks for the bug report.

Not having the intl extension installed would definitely cause this library to fail as it depends on the IDNA function [idna_to_ascii()](https://www.php.net/manual/en/function.idn-to-ascii.php) function that is provided by that extension. If this is a matter of the ICU version being too old (less than 4.6) then its going to be more complicated.

Strictly speaking, only IDNA 2008/UTS#46 is compatible with the WHATWG URL specification. Transforming a domain to ASCII in the spec leads you [here](https://url.spec.whatwg.org/#concept-domain-to-ascii), which then leads you to the [UTS#46 specification](https://www.unicode.org/reports/tr46/#ToASCII). I would like to avoid adding using IDNA 2003 given that it uses a different rule set to transform domains and is also deprecated.

According to the the [docs](https://www.php.net/manual/en/intl.constants.php#constant.intl-idna-variant-uts46) `INTL_IDNA_VARIANT_UTS46` requires an ICU version of at least 4.6 and it appears that PHP, prior to version 7.4, only requires [ICU version 4.0+](https://www.php.net/manual/en/intl.requirements.php).

According to the PHP 7.2 [upgrade docs](migration72.deprecated.INTL_IDNA_VARIANT_2003-variant) the use of the `INTL_IDNA_VARIANT_2003` constant is deprecated. In *theory* this should mean that hosting providers should be using ICU version 4.6+ for PHP 7.2 support, but that may not necessarily be the case according to the issue you linked.

In PHP 7.4, the `INTL_IDNA_VARIANT_UTS46` constant will become the default and the minimum ICU version required will be bumped to 50.1 according to the [upgrade docs](https://github.com/php/php-src/blob/php-7.4.0beta2/UPGRADING).

I did a quick test using `INTL_IDNA_VARIANT_2003` and PHPUnit came back with 12 errors and 38 failures.

Symfony recently added a [polyfill](https://github.com/symfony/polyfill-intl-idn) for the IDN functions, which might be a route to consider. If my theory about the minimum ICU version being raised in PHP 7.2 is correct, then the easiest thing to do would be to drop support for PHP 7.1 since its EOL date is [Dec 1, 2019](https://www.php.net/supported-versions.php).

I'll try doing some experiments with the Symfony polyfill to see if that would be a sufficient enough workaround.

**Comment by TRowbotham** [comment]
Unfortunately, after closer inspection, the Symfony polyfill is nothing more than an implementation of [Punycode](https://tools.ietf.org/html/rfc3492) with a few additional `if` statements tossed in. Using the polyfill initially reported 15 errors and 38 failures, but after adjusting for the polyfill's own quirks, the results were 9 errors and 43 failures.

**Comment by marcelklehr** [comment]
Thank your for the thorough investigation. As it happens, in the issue that brought my attention to this  the OP also uses php 7.2 to no avail, so I'm not sure if dropping support for php 7.1 will solve my particular issue, but I had little hope on that.

**Comment by TRowbotham** [comment]
You're welcome. I'm glad you find this library useful.

Your initial diagnosis was correct, it was an ancient version of the ICU library. I never would have imagined that a recent version of PHP would be using such an old version of ICU.

As much as I would really like to make this work for you, I think that consistency and correctness are paramount in a library like this. I think the best thing I could do in this situation is throw an exception if the `IDNA_INTL_VARIANT_UTS46` constant is not defined.
